fun main() {
  println("hi")
  println(smokeSummary())
  println(advancedSummary())
  println(localSummary())
  println(suspendSummary())
  println(delegateSummary())
  println(stateMachineSummary())
  println(delayedStateSummary())
  println(stateExceptionSummary())
  println(bytecodeSummary())
  println(threadedStateSummary())
  println(executorStateSummary())
  println(dispatchedStateSummary())
}
