fun main() {
  println("hi")
  println(smokeSummary())
  println(advancedSummary())
  println(localSummary())
  println(delegateSummary())
  println(bytecodeSummary())
  println(referenceSequenceSummary())
  println(valueClassSummary())
  println(reifiedArraySummary())
  println(annotationReflectionSummary())
  println(modernConstructSummary())
  println(inlineControlSummary())
  println(jvmInteropSummary())
  println(mutableDelegateSummary())
}
